tabla_simbolos = [
    {'token':'&&','descrip':'Operador logico'},
    {'token':'||','descrip':'Operador logico'},
    {'token':'!','descrip':'Operador logico'},
    {'token':'=','descrip':'Operador asignación'},
    {'token':'%=','descrip':'Operador asignación'},
    {'token':'*=','descrip':'Operador asignación'},
    {'token':'/=','descrip':'Operador asignación'},
    {'token':'+=','descrip':'Operador asignación'},
    {'token':'-=','descrip':'Operador asignación'},
    {'token':'-','descrip':'Operador aritmetico'},
    {'token':'--','descrip':'Operador aritmetico'},
    {'token':'+','descrip':'Operador aritmetico'},
    {'token':'++','descrip':'Operador aritmetico'},
    {'token':'*','descrip':'Operador aritmetico'},
    {'token':'/','descrip':'Operador aritmetico'},
    {'token':'%','descrip':'Operador aritmetico'},
    {'token':'<','descrip':'Operador comparacion'},
    {'token':'>','descrip':'Operador comparacion'},
    {'token':'<=','descrip':'Operador comparacion'},
    {'token':'>=','descrip':'Operador comparacion'},
    {'token':'==','descrip':'Operador comparacion'},
    {'token':'!=','descrip':'Operador comparacion'},
    {'token':'[','descrip':'Simbolo'},
    {'token':']','descrip':'Simbolo'},
    {'token':'(','descrip':'Simbolo'},
    {'token':')','descrip':'Simbolo'},
    {'token':'{','descrip':'Simbolo'},
    {'token':'}','descrip':'Simbolo'},
    {'token':':', 'descrip':'Simbolo'},
    {'token':'\"', 'descrip':'Simbolo'},
    {'token':'\'', 'descrip':'Simbolo'},
    {'token':'.', 'descrip':'Simbolo'},
    {'token':',','descrip':'Simbolo'},
    {'token':';','descrip':'Simbolo'},
    {'token':'void','descrip':'Tipo dato'},
    {'token':'int','descrip':'Tipo dato'},
    {'token':'float','descrip':'Tipo dato'},
    {'token':'char','descrip':'Tipo dato'},
    {'token':'boolean','descrip':'Tipo dato'},
    {'token':'byte','descrip':'Tipo dato'},
    {'token':'float','descrip':'Tipo dato'},
    {'token':'double','descrip':'Tipo dato'},
    {'token':'long','descrip':'Tipo dato'},
    {'token':'if','descrip':'Sentencia'},
    {'token':'else','descrip':'Sentencia'},
    {'token':'while','descrip':'Sentencia'},
    {'token':'for','descrip':'Sentencia'},
    {'token':'break','descrip':'Sentencia'},
    {'token':'continue','descrip':'Sentencia'},
    {'token':'return','descrip':'Sentencia'},
    {'token':'switch','descrip':'Sentencia'},
    {'token':'case','descrip':'Sentencia'},
    {'token':'do','descrip':'Sentencia'},
    {'token':'try','descrip':'Sentencia'},
    {'token':'catch','descrip':'Sentencia'},
    {'token':'finally','descrip':'Sentencia'},
    {'token':'throw','descrip':'Sentencia'},
    {'token':'throws','descrip':'Sentencia'},
    {'token':'super','descrip':'Sentencia'},
    {'token':'interface','descrip':'Definicion'},
    {'token':'abstract','descrip':'Definicion'},
    {'token':'class','descrip':'Definicion'},
    {'token':'new','descrip':'Definicion'},
    {'token':'import','descrip':'Definicion'},
    {'token':'extends','descrip':'Definicion'},
    {'token':'implements','descrip':'Definicion'},
    {'token':'package','descrip':'Definicion'},
    {'token':'public','descrip':'Encapsulamiento'},
    {'token':'private','descrip':'Encapsulamiento'},
    {'token':'protected','descrip':'Encapsulamiento'},
    {'token':'final','descrip':'Encapsulamiento'},
    {'token':'static','descrip':'Encapsulamiento'},
    {'token':'*','descrip':'Operador apuntador'},
    {'token':'&','descrip':'Operador apuntador'},
    {'token':'this','descrip':'Operador apuntador'},
    {'token':'\n', 'descrip':'Secuencia escape'},
    {'token':'\b', 'descrip':'Secuencia escape'},
    {'token':'\t', 'descrip':'Secuencia escape'},
    {'token':'\f', 'descrip':'Secuencia escape'},
    {'token':'\\', 'descrip':'Secuencia escape'},
    {'token':'\r', 'descrip':'Secuencia escape'},
    {'token':'\'', 'descrip':'Secuencia escape'},
]
