tabla_simbolos = [
    {'token':'AND','descrip':'Operador logico'},
    {'token':'OR','descrip':'Operador logico'},
    {'token':'!','descrip':'Operador logico'},
    {'token':'=','descrip':'Operador asignación'},
    {'token':'=','descrip':'Operador asignación'},
    {'token':'*=','descrip':'Operador asignación'},
    {'token':'/=','descrip':'Operador asignación'},
    {'token':'+=','descrip':'Operador asignación'},
    {'token':'-=','descrip':'Operador asignación'},
    {'token':'-','descrip':'Operador aritmetico'},
    {'token':'--','descrip':'Operador aritmetico'},
    {'token':'+','descrip':'Operador aritmetico'},
    {'token':'++','descrip':'Operador aritmetico'},
    {'token':'*','descrip':'Operador aritmetico'},
    {'token':'/','descrip':'Operador aritmetico'},
    {'token':'MOD','descrip':'Operador aritmetico'},
    {'token':'<','descrip':'Operador comparacion'},
    {'token':'>','descrip':'Operador comparacion'},
    {'token':'<=','descrip':'Operador comparacion'},
    {'token':'>=','descrip':'Operador comparacion'},
    {'token':'==','descrip':'Operador comparacion'},
    {'token':'!=','descrip':'Operador comparacion'},
    {'token':'[','descrip':'Simbolo'},
    {'token':']','descrip':'Simbolo'},
    {'token':'(','descrip':'Simbolo'},
    {'token':')','descrip':'Simbolo'},
    {'token':'{','descrip':'Simbolo'},
    {'token':'}','descrip':'Simbolo'},
    {'token':':', 'descrip':'Simbolo'},
    {'token':'\"', 'descrip':'Simbolo'},
    {'token':'\'', 'descrip':'Simbolo'},
    {'token':'.', 'descrip':'Simbolo'},
    {'token':',','descrip':'Simbolo'},
    {'token':';','descrip':'Simbolo'},
    {'token':'ENT','descrip':'Tipo dato'},
    {'token':'DEC','descrip':'Tipo dato'},
    {'token':'CARAC','descrip':'Tipo dato'},
    {'token':'VACIO','descrip':'Tipo dato'},
    {'token':'VIRTUAL','descrip':'Tipo dato'},
    {'token':'CADENA','descrip':'Tipo dato'},
    {'token':'SI','descrip':'Sentencia'},
    {'token':'ENTONCES','descrip':'Sentencia'},
    {'token':'MIENTRAS','descrip':'Sentencia'},
    {'token':'PARA','descrip':'Sentencia'},
    {'token':'ROMPER','descrip':'Sentencia'},
    {'token':'CONTINUAR','descrip':'Sentencia'},
    {'token':'RETORNAR','descrip':'Sentencia'},
    {'token':'FUNCION','descrip':'Definicion'},
    {'token':'CLASE','descrip':'Definicion'},
    {'token':'NUEVO','descrip':'Definicion'},
    {'token':'IMPORTAR','descrip':'Definicion'},
    {'token':'HEREDA','descrip':'Definicion'},
    {'token':'PUBLICO','descrip':'Encapsulamiento'},
    {'token':'PRIVADO','descrip':'Encapsulamiento'},
    {'token':'PROTEGIDO','descrip':'Encapsulamiento'},
    {'token':'<<','descrip':'Operador bit'},
    {'token':'>>','descrip':'Operador bit'},
    {'token':'*','descrip':'Operador apuntador'},
    {'token':'&','descrip':'Operador apuntador'},
    {'token':'\\n', 'descrip':'Secuencia escape'},
    {'token':'\\b', 'descrip':'Secuencia escape'},
    {'token':'\\t', 'descrip':'Secuencia escape'},
    {'token':'\\v', 'descrip':'Secuencia escape'},
    {'token':'\\', 'descrip':'Secuencia escape'},
    {'token':'\\f', 'descrip':'Secuencia escape'},
    {'token':'\\o', 'descrip':'Secuencia escape'},
]